ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.vialreport.backend.ApplicationKt.module ]
    }
}

database {
    url      = ${?DB_URL}
    user     = ${?DB_USER}
    password = ${?DB_PASSWORD}
    driver   = "com.mysql.cj.jdbc.Driver"
}

jwt {
    secret   = ${?JWT_SECRET}
    issuer   = ${?JWT_ISSUER}
    audience = ${?JWT_AUDIENCE}
    realm    = "VialReport"
}
